// Official Minecraft bee from Bedrock geometry.bee: feet-origin, +Y up,
// Z negated so the insect faces +z. The torso is already horizontal.
// Zero-thickness vanilla planes get a 0.4 texel so Skottie can paint them.
import { boxUv } from "./steve-model.mjs";

export const BEE_MODEL = [
  {
    id: "body",
    label: "Body",
    min: [-3, 2, -5],
    max: [4, 9, 5],
    pivot: [0.5, 5, 0],
    uv: boxUv(0, 0, 7, 7, 10),
  },
  {
    id: "antenna-right",
    label: "Right antenna",
    parent: "body",
    min: [2, 7, 5],
    max: [3, 9, 8],
    pivot: [0.5, 5, 0],
    uv: boxUv(2, 0, 1, 2, 3),
  },
  {
    id: "antenna-left",
    label: "Left antenna",
    parent: "body",
    min: [-2, 7, 5],
    max: [-1, 9, 8],
    pivot: [0.5, 5, 0],
    uv: boxUv(2, 3, 1, 2, 3),
  },
  {
    id: "stinger",
    label: "Stinger",
    parent: "body",
    min: [0.3, 5, -7],
    max: [0.7, 6, -5],
    pivot: [0.5, 5, 0],
    uv: boxUv(26, 7, 1, 1, 2),
  },
  {
    id: "wing-right",
    label: "Right wing",
    min: [-10, 8.6, 0],
    max: [-1, 9.2, 6],
    pivot: [-1, 9, 3],
    uv: boxUv(0, 18, 9, 1, 6),
  },
  {
    id: "wing-left",
    label: "Left wing",
    min: [2, 8.6, 0],
    max: [11, 9.2, 6],
    pivot: [2, 9, 3],
    uv: boxUv(9, 24, 9, 1, 6),
  },
  {
    id: "leg-front",
    label: "Front legs",
    parent: "body",
    min: [-3, 0, 1.8],
    max: [4, 2, 2.2],
    pivot: [0.5, 2, 2],
    uv: boxUv(26, 1, 7, 2, 1),
  },
  {
    id: "leg-mid",
    label: "Mid legs",
    parent: "body",
    min: [-3, 0, -0.2],
    max: [4, 2, 0.2],
    pivot: [0.5, 2, 0],
    uv: boxUv(26, 3, 7, 2, 1),
  },
  {
    id: "leg-back",
    label: "Back legs",
    parent: "body",
    min: [-3, 0, -2.2],
    max: [4, 2, -1.8],
    pivot: [0.5, 2, -2],
    uv: boxUv(26, 5, 7, 2, 1),
  },
];
