// Original CC0 16×16 item icons. Silhouettes stay sparse so swords and
// potions keep a holey outline; colors match the catalog tests.
import { blob, canvas, fillRect, hash32, setPx, shade, stamp, tile16 } from "./cc0-canvas.mjs";
import { paintBlock } from "./cc0-blocks.mjs";

const WOOD = "#c48a3a";
const STONE = "#8a8a8a";
const IRON = "#d0d4d8";
const GOLD = "#f0c838";
const DIAMOND = "#2aa8b8";
const NETHERITE = "#3a2a28";
const HANDLE = "#6a4220";

function art(rows, palette) {
  const img = tile16();
  stamp(img, rows, palette);
  return img;
}

function tool(kind, head) {
  const h = head;
  const s = shade(head, -28);
  const w = HANDLE;
  if (kind === "sword") {
    return art(
      `
...............H
..............HH
.............HHS
............HHS.
...........HHS..
..........HHS...
....#....HHS....
....##..HHS.....
.....###S.......
.....##S........
..#.##..........
.#.##...........
.##.............
#.#.............
.#..............
................
`,
      { H: h, S: s, "#": w },
    );
  }
  if (kind === "pickaxe") {
    return art(
      `
.....HHHHHH.....
....HH....HH....
...H........H...
............#...
...........#....
..........#.....
.........#......
........#.......
.......#........
......#.........
.....#..........
....#...........
...#............
................
................
................
`,
      { H: h, "#": w },
    );
  }
  if (kind === "axe") {
    return art(
      `
..........HHHH..
........HHHHHH..
.......HHHHHH...
......HHH..#....
..........#.....
.........#......
........#.......
.......#........
......#.........
.....#..........
....#...........
...#............
................
................
................
................
`,
      { H: h, "#": w },
    );
  }
  if (kind === "shovel") {
    return art(
      `
...........HH...
..........HHHH..
.........HHHHH..
..........HH#...
...........#....
..........#.....
.........#......
........#.......
.......#........
......#.........
.....#..........
....#...........
...#............
................
................
................
`,
      { H: h, "#": w },
    );
  }
  return art(
    `
.........HHHH...
........H.......
...........#....
..........#.....
.........#......
........#.......
.......#........
......#.........
.....#..........
....#...........
...#............
................
................
................
................
................
`,
    { H: h, "#": w },
  );
}

function armor(piece, hex) {
  const d = shade(hex, -24);
  const l = shade(hex, 20);
  if (piece === "helmet") {
    return art(
      `
....HHHHHHHH....
...HHHHHHHHHH...
..HH........HH..
..HH........HH..
..HH..HH..HH....
................
................
................
................
................
................
................
................
................
................
................
`,
      { H: hex },
    );
  }
  if (piece === "chestplate") {
    return art(
      `
..HH........HH..
..HHHHHHHHHHHH..
.HHHHHHHHHHHHHH.
.HHHHHHHHHHHHHH.
.HHHHHHHHHHHHHH.
.HHHHHHHHHHHHHH.
..HHHHHHHHHHHH..
..HHHHHHHHHHHH..
...HHHHHHHHHH...
................
................
................
................
................
................
................
`,
      { H: hex },
    );
  }
  if (piece === "leggings") {
    return art(
      `
.HHHHHHHHHHHHHH.
.HHHHHHHHHHHHHH.
.HHH........HHH.
.HHH........HHH.
.HHH........HHH.
.HHH........HHH.
.HHH........HHH.
.HHH........HHH.
................
................
................
................
................
................
................
................
`,
      { H: hex },
    );
  }
  return art(
    `
...HH......HH...
...HH......HH...
...HH......HH...
...HH......HH...
...HHHH..HHHH...
................
................
................
................
................
................
................
................
................
................
................
`,
    { H: hex, D: d, L: l },
  );
}

function ingot(hex) {
  return art(
    `
................
................
................
....HHHHHHHH....
...HHHHHHHHHH...
...HHHHHHHHHH...
....HHHHHHHH....
................
................
................
................
................
................
................
................
................
`,
    { H: hex },
  );
}

function gem(hex) {
  return art(
    `
................
........H.......
.......HHH......
......HHHHH.....
.....HHHHHHH....
......HHHHH.....
.......HHH......
........H.......
................
................
................
................
................
................
................
................
`,
    { H: hex },
  );
}

function potion() {
  return art(
    `
.......##.......
.......##.......
......#..#......
.....#....#.....
....#.RRRR.#....
....#RRRRRR#....
....#RRRRRR#....
.....#RRRR#.....
......####......
................
................
................
................
................
................
................
`,
    { "#": "#d0e0e8", R: "#e01818", ".": null },
  );
}

function bow(pull = -1) {
  const extra =
    pull < 0
      ? ""
      : pull === 0
        ? "......../.......\n"
        : pull === 1
          ? ".......//.......\n"
          : "......///.......\n";
  return art(
    `
.....#..........
....#.#.........
...#...#........
...#...#........
...#...#........
....#.#.........
.....#..........
......#.........
.......#........
........#.......
.........#......
................
................
................
................
................
`,
    { "#": "#6a4220", "/": "#e8e0d0" },
  );
}

const FOOD = {
  apple: `
......g.........
.....g.RR.......
....RRRRRR......
...RRRRRRRR.....
...RRRRRRRR.....
....RRRRRR......
.....RRRR.......
`,
  "golden-apple": `
......g.........
.....g.YY.......
....YYYYYY......
...YYYYYYYY.....
...YYYYYYYY.....
....YYYYYY......
.....YYYY.......
`,
  bread: `
................
...BBBBBBBB.....
..BBBBBBBBBB....
..BBBBBBBBBB....
...BBBBBBBB.....
`,
  steak: `
................
....MMMMMM......
...MMMMMMMM.....
...MM##MMMM.....
....MMMMMM......
`,
  "cooked-porkchop": `
................
....PPPPPP......
...PPPPPPPP.....
...PP##PPPP.....
....PPPPPP......
`,
  "cooked-chicken": `
................
.....CCCC.......
....CCCCCC......
....CC##CC......
.....CCCC.......
`,
  "cooked-mutton": `
................
....UUUUUU......
...UUUUUUUU.....
...UU##UUUU.....
....UUUUUU......
`,
  carrot: `
........g.......
.......gO.......
......OOOO......
.....OOOOO......
......OOO.......
`,
  potato: `
................
.....PPPP.......
....PPPPPP......
....PPPPPP......
.....PPPP.......
`,
  "baked-potato": `
................
.....BBBB.......
....BBBBBB......
....BBBBBB......
.....BBBB.......
`,
  cookie: `
................
.....CCCCC......
....CCCCCCC.....
....CCC#CCC.....
.....CCCCC......
`,
  "pumpkin-pie": `
................
....YYYYYY......
...YYYYYYYY.....
...YY####YY.....
....YYYYYY......
`,
  "melon-slice": `
................
.....RRRRR......
....RRGGGRR.....
....RGGGGGR.....
.....GGGGG......
`,
  cake: `
................
...WWWWWWWW.....
...RRRRRRRR.....
...WWWWWWWW.....
...=======......
`,
  "mushroom-stew": `
................
.....WWWWW......
....W.RR.BW.....
....WWWWWWW.....
......###.......
`,
};

const FOOD_PAL = {
  g: "#3a8a28",
  R: "#d02828",
  Y: "#f0c838",
  B: "#c48a42",
  M: "#8a4020",
  P: "#d08060",
  C: "#c88840",
  U: "#8a5030",
  O: "#e06020",
  G: "#5aaa38",
  W: "#f0e8e0",
  "#": "#6a4220",
  "=": "#d8c090",
};

const DROPS = {
  "rotten-flesh": `
................
....FFFFF.......
...FF.FFFF......
...FFFFFFF......
....FFFFF.......
`,
  bone: `
...............W
..............WW
.............WW.
............WW..
...........WW...
..........WW....
.........WW.....
........WW......
.......WW.......
......WW........
.....WW.........
....WW..........
...WW...........
..WW............
.W..............
`,
  string: `
....s...........
.....s..........
......s.s.......
.......s........
......s.s.......
.....s..........
`,
  gunpowder: `
................
.....#####......
....#######.....
....#######.....
.....#####......
`,
  "spider-eye": `
................
......WWW.......
.....W#R#W......
......WWW.......
`,
  "ender-pearl": `
................
......EEE.......
.....EEEEE......
.....EEEEE......
......EEE.......
`,
  feather: `
........w.......
.......www......
......ww#w......
.....ww#w.......
....ww#w........
...w##..........
`,
  wheat: `
.......Y........
......Y.Y.......
.....Y.#.Y......
......#.#.......
.......#........
.......#........
`,
  coal: `
................
......###.......
.....#####......
.....#####......
......###.......
`,
  charcoal: `
................
......###.......
.....#####......
.....###.#......
......###.......
`,
  flint: `
................
......###.......
.....#####......
....######......
.....####.......
`,
  stick: `
............#...
...........#....
..........#.....
.........#......
........#.......
.......#........
......#.........
`,
  shears: `
....#......#....
.....#....#.....
......#..#......
.......##.......
......#..#......
.....#....#.....
`,
  "flint-and-steel": `
....ssss........
...s....s.......
...s....s..#....
....ssss..#.....
.........#......
`,
  arrow: `
...............#
..............#H
.............#H.
............#H..
...........#....
..........#.....
.........#......
........#.......
.......F........
`,
  saddle: `
................
....SSSSSS......
...SS####SS.....
...SSSSSSSS.....
....S....S......
`,
  leather: `
................
....LLLLL.......
...LLLLLLL......
...LLLLLLL......
....LLLLL.......
`,
  slimeball: `
................
.....GGGG.......
....GGGGGG......
....GGGGGG......
.....GGGG.......
`,
  bucket: `
................
....#......#....
....#......#....
....########....
.....######.....
`,
  "water-bucket": `
................
....#......#....
....#~~~~~~#....
....########....
.....######.....
`,
  "lava-bucket": `
................
....#......#....
....#!!!!!!#....
....########....
.....######.....
`,
  "milk-bucket": `
................
....#......#....
....#MMMMMM#....
....########....
.....######.....
`,
  bowl: `
................
....#......#....
....########....
.....######.....
`,
  egg: `
................
......EEE.......
.....EEEEE......
.....EEEEE......
......EEE.......
`,
  snowball: `
................
......WWW.......
.....WWWWW......
.....WWWWW......
......WWW.......
`,
  sugar: `
................
......sss.......
.....sssss......
......sss.......
`,
  paper: `
................
....PPPPPP......
....PPPPPP......
....PPPPPP......
....PPPPPP......
`,
  book: `
................
....BBBBBB......
....B.B.BB......
....BBBBBB......
....######......
`,
  "glowstone-dust": `
................
.....YYYY.......
....YYYYYY......
.....YYYY.......
`,
  quartz: `
................
......QQQ.......
.....QQQQQ......
......QQQ.......
`,
  "nether-wart": `
................
......NNN.......
.....NNNNN......
......N.N.......
`,
  "netherite-scrap": `
................
.....NNNN.......
....NNN.NN......
.....NNNN.......
`,
  "netherite-ingot": `
................
....NNNNNNNN....
...NNNNNNNNNN...
....NNNNNNNN....
`,
  "music-disc": `
................
.....#####......
....##...##.....
....#..C..#.....
....##...##.....
.....#####......
`,
  "oak-door": `
....WWWWWW......
....W....W......
....W....W......
....W.#..W......
....WWWWWW......
....WWWWWW......
`,
  "wheat-seeds": `
................
.....s.s.s......
......s.s.......
.....s.s.s......
`,
  "cocoa-beans": `
................
.....bbb........
....bbbbb.......
.....bbb........
`,
  "bone-meal": `
................
.....WWW........
....WWWWW.......
.....WWW........
`,
  lapis: `
................
......LLL.......
.....LLLLL......
......LLL.......
`,
  "redstone-dust": `
................
.....rrr.r......
....r.rrr.......
.....r.r.r......
`,
  emerald: `
................
.......E........
......EEE.......
.....EEEEE......
......EEE.......
.......E........
`,
  "iron-nugget": `
................
......II........
.....IIII.......
......II........
`,
  "gold-nugget": `
................
......YY........
.....YYYY.......
......YY........
`,
  "copper-ingot": `
................
....CCCCCCCC....
...CCCCCCCCCC...
....CCCCCCCC....
`,
  "fishing-rod": `
............#...
...........#s...
..........#..s..
.........#......
........#.......
.......#........
`,
  "raw-cod": `
................
....fffff.......
...fff#ffff.....
....fffff.......
`,
  "cooked-cod": `
................
....CCCCC.......
...CCC#CCCC.....
....CCCCC.......
`,
  porkchop: `
................
....pppppp......
...pppppppp.....
...pp##pppp.....
....pppppp......
`,
  beef: `
................
....mmmmmm......
...mmmmmmmm.....
...mm##mmmm.....
....mmmmmm......
`,
  "raw-chicken": `
................
.....cccc.......
....cccccc......
....cc##cc......
.....cccc.......
`,
  "raw-mutton": `
................
....uuuuuu......
...uuuuuuuu.....
...uu##uuuu.....
....uuuuuu......
`,
};

const DROP_PAL = {
  F: "#e85858",
  "#": "#2a2a2a",
  s: "#d0d0c8",
  W: "#f0f0ea",
  R: "#d02828",
  E: "#48c0a8",
  w: "#f8f8f8",
  Y: "#e0c040",
  S: "#6a3a18",
  L: "#8a4a28",
  G: "#58c048",
  "~": "#3a6ec8",
  "!": "#e05010",
  M: "#f0f0ea",
  P: "#f0efe8",
  B: "#3060b0",
  Q: "#f0e8e0",
  N: "#4a3028",
  C: "#c87040",
  r: "#d01818",
  I: "#d0d4d8",
  f: "#90a8b8",
  p: "#e09080",
  m: "#b04030",
  c: "#e8d0b0",
  u: "#c07070",
  b: "#6a3a18",
  g: "#3a8a28",
  H: "#c8c8c8",
};

const MATERIALS = {
  wood: WOOD,
  stone: STONE,
  iron: IRON,
  gold: GOLD,
  diamond: DIAMOND,
  netherite: NETHERITE,
  wooden: WOOD,
  chainmail: "#8a9098",
  leather: "#8a4a28",
};

const TOOLS = ["sword", "pickaxe", "axe", "shovel", "hoe"];
const ARMOR = ["helmet", "chestplate", "leggings", "boots"];

const BLOCK_IDS = new Set(["dirt", "cobblestone", "oak-planks", "stone", "sand", "oak-log", "torch", "bricks", "pumpkin"]);

export function paintItem(id) {
  if (BLOCK_IDS.has(id)) return paintBlock(id);

  for (const mat of Object.keys(MATERIALS)) {
    for (const toolName of TOOLS) {
      if (id === `${mat}-${toolName}` || id === `${mat === "wood" ? "wooden" : mat}-${toolName}`) {
        return tool(toolName, MATERIALS[mat] ?? MATERIALS.wooden);
      }
    }
    for (const piece of ARMOR) {
      if (id === `${mat}-${piece}`) return armor(piece, MATERIALS[mat]);
    }
  }

  if (id === "diamond") return gem(DIAMOND);
  if (id === "potion-heal") return potion();
  if (id === "bow") return bow(-1);
  if (id === "bow-0") return bow(0);
  if (id === "bow-1") return bow(1);
  if (id === "bow-2") return bow(2);
  if (id === "iron-ingot") return ingot(IRON);
  if (id === "gold-ingot") return ingot(GOLD);
  if (FOOD[id]) return art(FOOD[id], FOOD_PAL);
  if (DROPS[id]) return art(DROPS[id], { ...FOOD_PAL, ...DROP_PAL });

  const img = tile16();
  blob(img, 8, 8, 4, 4, "#808080");
  return img;
}

const FILE_TO_ID = {
  "diamond_sword.png": "diamond-sword",
  "stone_sword.png": "stone-sword",
  "wood_sword.png": "wooden-sword",
  "iron_sword.png": "iron-sword",
  "bow_standby.png": "bow",
  "bow_pulling_0.png": "bow-0",
  "bow_pulling_1.png": "bow-1",
  "bow_pulling_2.png": "bow-2",
  "arrow.png": "arrow",
  "trident.png": "trident",
  "crossbow_standby.png": "crossbow",
  "diamond_pickaxe.png": "diamond-pickaxe",
  "diamond_axe.png": "diamond-axe",
  "diamond_shovel.png": "diamond-shovel",
  "diamond_hoe.png": "diamond-hoe",
};

export function paintItemFile(file) {
  if (FILE_TO_ID[file]) return paintItem(FILE_TO_ID[file]);
  if (file.includes("trident")) {
    return art(
      `
...............#
..............##
.............##.
............##..
...........##...
..........##....
.........##.....
........##......
.......##.......
......##........
.....##.........
....##..........
...#............
................
................
................
`,
      { "#": "#6ad0c8" },
    );
  }
  if (file.includes("crossbow")) {
    return art(
      `
....#......#....
.....#....#.....
......#..#......
.......##.......
......#..#......
.....#....#.....
....#......#....
.......##.......
.......##.......
`,
      { "#": "#6a4220" },
    );
  }
  const stem = file.replace(/\.png$/, "").replace(/_/g, "-");
  return paintItem(stem);
}

export function paintXpOrb() {
  const img = tile16();
  blob(img, 8, 8, 5, 5, "#48e030");
  blob(img, 7, 7, 2, 2, "#c8ff80");
  return img;
}
