// Official Minecraft rabbit from Bedrock geometry.rabbit.v1.8: feet-origin,
// +Y up, Z negated so the animal faces +z. The body is already a long
// horizontal cuboid, so poses do not apply a 90° rest pitch.
import { boxUv } from "./steve-model.mjs";

export const RABBIT_MODEL = [
  {
    id: "body",
    label: "Body",
    min: [-3, 2, -8],
    max: [3, 7, 2],
    pivot: [0, 5, -3],
    uv: boxUv(0, 0, 6, 5, 10),
  },
  {
    id: "head",
    label: "Head",
    min: [-2.5, 8, 1],
    max: [2.5, 12, 6],
    pivot: [0, 8, 1],
    uv: boxUv(32, 0, 5, 4, 5),
  },
  {
    id: "nose",
    label: "Nose",
    parent: "head",
    min: [-0.5, 9.5, 5.5],
    max: [0.5, 10.5, 6.5],
    pivot: [0, 8, 1],
    uv: boxUv(32, 9, 1, 1, 1),
  },
  {
    id: "ear-right",
    label: "Right ear",
    parent: "head",
    min: [-2.5, 12, 1],
    max: [-0.5, 17, 2],
    pivot: [0, 8, 1],
    uv: boxUv(58, 0, 2, 5, 1),
  },
  {
    id: "ear-left",
    label: "Left ear",
    parent: "head",
    min: [0.5, 12, 1],
    max: [2.5, 17, 2],
    pivot: [0, 8, 1],
    uv: boxUv(52, 0, 2, 5, 1),
  },
  {
    id: "leg-front-right",
    label: "Front right leg",
    min: [-4, 0, 0],
    max: [-2, 7, 2],
    pivot: [-3, 7, 1],
    uv: boxUv(0, 15, 2, 7, 2),
  },
  {
    id: "leg-front-left",
    label: "Front left leg",
    min: [2, 0, 0],
    max: [4, 7, 2],
    pivot: [3, 7, 1],
    uv: boxUv(8, 15, 2, 7, 2),
  },
  {
    id: "haunch-right",
    label: "Right haunch",
    min: [-4, 2.5, -8.7],
    max: [-2, 6.5, -3.7],
    pivot: [-3, 6.5, -3.7],
    uv: boxUv(30, 15, 2, 4, 5),
  },
  {
    id: "haunch-left",
    label: "Left haunch",
    min: [2, 2.5, -8.7],
    max: [4, 6.5, -3.7],
    pivot: [3, 6.5, -3.7],
    uv: boxUv(16, 15, 2, 4, 5),
  },
  {
    id: "foot-right",
    label: "Right hind foot",
    parent: "haunch-right",
    min: [-4, 0, -7],
    max: [-2, 1, 0],
    pivot: [-3, 6.5, -3.7],
    uv: boxUv(26, 24, 2, 1, 7),
  },
  {
    id: "foot-left",
    label: "Left hind foot",
    parent: "haunch-left",
    min: [2, 0, -7],
    max: [4, 1, 0],
    pivot: [3, 6.5, -3.7],
    uv: boxUv(8, 24, 2, 1, 7),
  },
  {
    id: "tail",
    label: "Tail",
    min: [-1.5, 2.5, -9],
    max: [1.5, 5.5, -7],
    pivot: [0, 4, -7],
    uv: boxUv(52, 6, 3, 3, 2),
  },
];
