import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

function repoPath(url) {
  return resolve(ROOT, "assets", url.replace(/^\/repo-assets\//, ""));
}

describe("html game demo", () => {
  it("ships a standalone page that loads vanilla JS", async () => {
    const html = await readFile(resolve(ROOT, "public/game/index.html"), "utf8");
    const game = await readFile(resolve(ROOT, "public/game/game.js"), "utf8");
    const css = await readFile(resolve(ROOT, "public/game/style.css"), "utf8");
    assert.match(html, /id="game"/);
    assert.match(html, /id="start"/);
    assert.match(html, /id="demo"/);
    assert.match(html, /src="\/game\/game\.js"/);
    assert.match(html, /href="\/game\/style\.css"/);
    assert.match(html, /type="module"/);
    assert.match(game, /from "\.\/recipes\.js"/);
    assert.match(game, /from "\.\/levels\.js"/);
    assert.match(game, /function startLevel/);
    assert.match(game, /function checkQuest/);
    assert.match(game, /function questHud/);
    assert.match(game, /function nextLevel/);
    assert.match(game, /WORLD_BUILDERS/);
    assert.match(game, /buildFarmWorld/);
    assert.match(game, /buildFishWorld/);
    assert.match(game, /buildNetherWorld/);
    assert.match(html, /id="level-list"/);
    assert.match(html, /七个关卡/);
    assert.match(html, /通关后按/);
    assert.match(css, /\.level-btn/);
    assert.match(game, /tryAddItem/);
    assert.match(game, /捡不了/);
    assert.match(game, /function throwSelected/);
    assert.match(game, /setCell\(tiles, 62, ground - 1, "D"\)/);
    assert.match(html, /扔掉快捷栏/);
    assert.match(game, /tryOpenTable|craftingOpen/);
    assert.match(game, /function tryOpenChest/);
    assert.match(game, /chestOpen/);
    assert.match(game, /function tryOpenFurnace/);
    assert.match(game, /furnaceOpen/);
    assert.match(game, /function tryOpenBrew/);
    assert.match(game, /brewOpen/);
    assert.match(game, /function tryEnchant/);
    assert.match(game, /function tryEatCake/);
    assert.match(game, /function tryBuildGolem/);
    assert.match(game, /function tryJukebox/);
    assert.match(game, /function tryThrowTrident/);
    assert.match(game, /furnaceTick/);
    assert.match(game, /function tryToggleDoor/);
    assert.match(game, /function tryGadget/);
    assert.match(game, /function drawClouds/);
    assert.match(game, /function pulseFrom/);
    assert.match(game, /function tryBeacon/);
    assert.match(game, /function tryAnvil/);
    assert.match(game, /function trySmith/);
    assert.match(game, /function tryTrade/);
    assert.match(game, /function tryFirework/);
    assert.match(game, /function conductRedstone/);
    assert.match(game, /function buildEnd/);
    assert.match(game, /doorOpen/);
    assert.match(game, /function tryBucket/);
    assert.match(game, /function tryShear/);
    assert.match(game, /function tryFlint/);
    assert.match(game, /function refreshArmor/);
    assert.match(game, /steve-sprites\/armor-/);
    assert.match(game, /blocks\/chest-open\.svg/);
    assert.match(game, /blocks\/door-oak-open\.svg/);
    assert.match(game, /flint-and-steel/);
    assert.match(game, /makeMob\("chicken"/);
    assert.match(game, /makeMob\("sheep"/);
    assert.match(game, /makeMob\("wolf"/);
    assert.match(game, /makeMob\("slime"/);
    assert.match(game, /makeMob\("rabbit"/);
    assert.match(game, /makeMob\("villager"/);
    assert.match(game, /makeMob\("cat"/);
    assert.match(game, /makeMob\("bat"/);
    assert.match(game, /makeMob\("squid"/);
    assert.match(game, /makeMob\("witch"/);
    assert.match(game, /makeMob\("iron-golem"/);
    assert.match(game, /makeMob\("horse"/);
    assert.match(game, /makeMob\("boat"/);
    assert.match(game, /makeMob\("blaze"/);
    assert.match(game, /makeMob\("ghast"/);
    assert.match(game, /makeMob\("wither-skeleton"/);
    assert.match(game, /makeMob\("snow-golem"/);
    assert.match(game, /makeMob\("drowned"/);
    assert.match(game, /makeMob\("pillager"/);
    assert.match(game, /makeMob\("minecart"/);
    assert.match(game, /makeMob\("wither"/);
    assert.match(game, /makeMob\("ender-dragon"/);
    assert.match(game, /makeMob\("fox"/);
    assert.match(game, /makeMob\("parrot"/);
    assert.match(game, /makeMob\("bee"/);
    assert.match(game, /function tryHive/);
    assert.match(game, /function tryPlaceMinecart/);
    assert.match(game, /function tryLead/);
    assert.match(game, /function tryBuildWither/);
    assert.match(game, /function hasElytra/);
    assert.match(game, /function consumeTotem/);
    assert.match(game, /function buildEnd/);
    assert.match(game, /dimension === "end"/);
    assert.match(game, /makeMob\("magma-cube"/);
    assert.match(game, /function swapOffhand/);
    assert.match(game, /offhand/);
    assert.match(game, /door-sprites\/swing-/);
    assert.match(game, /steve-sprites\/shield-hold/);
    assert.match(game, /nether-wart/);
    assert.match(game, /function updateDoors/);
    assert.match(game, /function fireFireball/);
    assert.match(html, /副手/);
    assert.match(game, /function buildNether/);
    assert.match(game, /function swapDimension/);
    assert.match(game, /function tryMount/);
    assert.match(game, /function trySaddle/);
    assert.match(game, /function tryPlaceBoat/);
    assert.match(game, /function updatePortal/);
    assert.match(game, /function tryFish/);
    assert.match(game, /function drawRain/);
    assert.match(game, /function isRaining/);
    assert.match(game, /armor-netherite/);
    assert.match(game, /function tryThrowPearl/);
    assert.match(game, /function addXp/);
    assert.match(game, /armor-gold/);
    assert.match(game, /shorn-/);
    assert.match(game, /"V"/);
    assert.match(game, /bow-pulling-/);
    assert.match(game, /hud\/bubble\.svg/);
    assert.match(game, /water-bucket/);
    assert.match(game, /function firePlayerBow/);
    assert.match(game, /function heldOverlayId/);
    assert.match(game, /from: "player"/);
    assert.match(game, /raw-porkchop/);
    assert.match(game, /"H"/);
    assert.match(game, /"R"/);
    assert.doesNotMatch(game, /holdingSword\(\) return "steve-sprites\/swing-0/);
    assert.match(game, /transferStack/);
    assert.match(game, /放进了箱子/);
    assert.doesNotMatch(game, /player\.atChest && !win/);
    assert.match(game, /imageSmoothingEnabled = false/);
    assert.match(game, /BLOCK_SRC_PAD = 56/);
    assert.match(game, /BLOCK_SRC_FACE = 400/);
    assert.match(game, /function drawTile/);
    assert.match(game, /function supportedByFloor/);
    assert.match(game, /function swimBody/);
    assert.match(game, /water-sprites\/flow-/);
    assert.match(game, /body\.air/);
    assert.match(game, /body\.drownT/);
    assert.match(game, /TILE \+ 1/);
    assert.match(game, /player\.knockT/);
    assert.match(game, /requestAnimationFrame\(frame\)/);
    assert.match(game, /netherrack/);
    assert.match(game, /soul-sand/);
    assert.match(game, /function trySmelt/);
    assert.match(game, /function tryShoot/);
    assert.match(game, /function explodeAt/);
    assert.match(game, /function tryTill/);
    assert.match(game, /function tryBoneMeal/);
    assert.match(game, /function tryFish/);
    assert.match(game, /player\.level/);
    assert.match(html, /冲刺/);
    assert.match(html, /骨粉/);
    assert.match(game, /furnace-on/);
    assert.match(game, /heart-flash/);
    assert.match(html, /27 格背包/);
    assert.match(html, /床边重生/);
    assert.match(game, /function respawnPlayer/);
    assert.match(game, /function dropInventory/);
    assert.match(game, /PLAYER_SLOTS/);
    assert.match(game, /bedSpawn/);
    assert.match(game, /function wearHeld/);
    assert.match(game, /canHarvest/);
    assert.match(game, /按 R 重生/);
    assert.match(html, /按住挖掘/);
    assert.match(game, /function finishMineCell/);
    assert.match(game, /function fireBow/);
    assert.match(game, /function drawBubbles/);
    assert.match(game, /function drawActionProgress/);
    assert.match(game, /hud\/bubble\.svg/);
    assert.match(game, /hud\/progress-bar\.svg/);
    assert.match(game, /items\/bow-0\.svg/);
    assert.match(game, /blocks\/destroy-\$\{/);
    assert.doesNotMatch(game, /ctx\.filter/);
    assert.match(css, /image-rendering:\s*pixelated/);
  });

  it("preloads existing repo art instead of inventing new sprites", async () => {
    const src = await readFile(resolve(ROOT, "public/game/game.js"), "utf8");
    const rels = new Set();
    for (const match of src.matchAll(/["']((?:blocks|items|hud|steve-sprites|zombie-sprites|skeleton-sprites|spider-sprites|enderman-sprites|creeper-sprites|pig-sprites|cow-sprites|chicken-sprites|sheep-sprites|slime-sprites|lava-sprites|water-sprites)\/[a-z0-9-]+\.svg)["']/g)) {
      rels.add(match[1]);
    }
    const steve = ["idle-a", "idle-b", ...Array.from({ length: 8 }, (_, i) => `run-${i}`), "jump-crouch", "jump-rise", "jump-apex", "jump-fall", "jump-land"];
    for (const id of steve) rels.add(`steve-sprites/${id}.svg`);
    for (let i = 0; i < 10; i++) rels.add(`steve-sprites/swing-${i}.svg`);
    for (let i = 0; i < 8; i++) rels.add(`steve-sprites/hurt-${i}.svg`);
    for (let i = 0; i < 12; i++) rels.add(`steve-sprites/death-${i}.svg`);
    for (let i = 0; i < 8; i++) rels.add(`steve-sprites/sleep-${i}.svg`);
    for (let i = 0; i < 8; i++) rels.add(`steve-sprites/eat-${i}.svg`);
    for (const mob of ["zombie", "skeleton", "spider", "enderman", "creeper", "pig", "cow", "chicken", "sheep", "slime"]) {
      for (let i = 0; i < 8; i++) rels.add(`${mob}-sprites/walk-${i * 2}.svg`);
    }
    for (const mob of ["zombie", "skeleton", "spider", "enderman", "creeper", "pig", "cow", "chicken", "sheep", "slime"]) {
      for (let i = 0; i < 8; i++) rels.add(`${mob}-sprites/idle-${i}.svg`);
    }
    for (const mob of ["zombie", "skeleton", "spider", "enderman", "creeper", "pig", "cow", "chicken", "sheep", "slime"]) {
      for (let i = 0; i < 8; i++) rels.add(`${mob}-sprites/hurt-${i}.svg`);
    }
    for (const mob of ["zombie", "skeleton", "spider", "enderman", "creeper", "drowned"]) {
      for (let i = 0; i < 12; i++) rels.add(`${mob}-sprites/death-${i}.svg`);
    }
    for (let i = 0; i < 12; i++) rels.add(`skeleton-sprites/draw-${i}.svg`);
    rels.add("items/arrow.svg");
    for (const mob of ["pig", "cow", "chicken", "sheep", "slime"]) {
      for (let i = 0; i < 8; i++) {
        if (mob !== "slime") rels.add(`${mob}-sprites/rest-${i}.svg`);
        rels.add(`${mob}-sprites/death-${i}.svg`);
      }
    }
    for (let i = 0; i < 10; i++) rels.add(`creeper-sprites/swell-${i * 2}.svg`);
    for (let i = 0; i < 8; i++) rels.add(`lava-sprites/boil-${i * 4}.svg`);
    for (let i = 0; i < 8; i++) rels.add(`water-sprites/flow-${i * 4}.svg`);
    const itemIds = [...src.matchAll(/["'](diamond-sword|diamond-pickaxe|diamond-axe|diamond-hoe|bow|arrow|torch|bread|steak|apple|golden-apple|potion-heal|diamond|cooked-porkchop|raw-porkchop|raw-beef|wheat-seeds|carrot|wheat)["']/g)].map((m) => m[1]);
    for (const id of new Set(itemIds)) rels.add(`items/${id}.svg`);
    assert.ok(rels.size >= 40, `expected a full loadout, got ${rels.size}`);
    for (const rel of rels) {
      assert.ok(existsSync(resolve(ROOT, "assets", rel)), `missing ${rel}`);
    }
    assert.ok(rels.has("blocks/grass.svg"));
    assert.ok(rels.has("hud/hotbar.svg"));
    assert.ok(rels.has("items/diamond-sword.svg"));
    assert.ok(rels.has("blocks/furnace.svg") || src.includes("furnace"));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/furnace-on.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/iron-ore.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/raw-porkchop.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/diamond-hoe.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/bow-pulling-2.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/hud/bubble.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/hud/bubble-empty.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/wooden-pickaxe.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/wheat-6.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/chest-open.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/door-oak-open.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/fire.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/shield.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/leather-helmet.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/steve-sprites/armor-leather.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/chicken-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/sheep-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/wolf-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/steve-sprites/armor-gold.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/steve-sprites/armor-iron-run-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/fire-3.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/tnt-primed.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/xp-orb.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/flint.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/charcoal.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/sugar-cane.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/rabbit-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/villager-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/sheep-sprites/shorn-idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/cat-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/bat-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/squid-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/witch-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/iron-golem-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/horse-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/boat-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blaze-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/magma-cube-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/ghast-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/wither-skeleton-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/snow-golem-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/drowned-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/pillager-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/minecart-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/wither-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/ender-dragon-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/trident.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/crossbow.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/music-disc-13.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/music-disc-cat.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/jukebox.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/carrot-3.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/potato-3.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/rail.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/end-stone.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/end-portal.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/minecart.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/lead.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/elytra.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/totem.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/nether-star.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/wither-skull.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/door-sprites/swing-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/steve-sprites/shield-hold.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/steve-sprites/shield-block.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/nether-wart.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/ghast-tear.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/glass-bottle.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/potion-fire.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/cake.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/cake.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/brewing-stand.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/nether-wart-3.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/oak-boat.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/blaze-rod.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/nether-portal.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/cloud.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/piston-head.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/door-iron-upper.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/spruce-log.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/birch-log.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/iron-door-sprites/swing-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/beacon.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/anvil.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/ender-chest.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/lever.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/powered-rail.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/powered-rail-on.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/smithing-table.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/firework.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/chorus-fruit.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/netherite-ingot.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/netherite-sword.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/honey-bottle.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/sweet-berries.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/beehive.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/honey-block.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/fox-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/parrot-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/bee-sprites/idle-0.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/steve-sprites/armor-netherite.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/items/fishing-rod.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/bookshelf.svg")));
    assert.ok(existsSync(resolve(ROOT, "assets/blocks/obsidian.svg")));
  });

  it("serves those files from /repo-assets/", async () => {
    const plugin = await readFile(resolve(ROOT, "vite-plugins/repo-assets.ts"), "utf8");
    const vite = await readFile(resolve(ROOT, "vite.config.ts"), "utf8");
    assert.match(plugin, /\/repo-assets\//);
    assert.match(plugin, /Location.*\/game\//);
    assert.match(vite, /repoAssetsPlugin/);
  });
});
